### POST request to create patient
POST http://lb-cd183759.elb.localhost.localstack.cloud:4000/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Joe2 with analytics account",
  "email": "joe2_account_analytics_billing20@example.com",
  "address": "123 t str",
  "dateOfBirth": "2000-01-01",
  "registeredDate": "2025-12-25"
}

###